### 1)

2) We performed a pore analysis of IRMOF-1, with a probe radius of 1.525 Angstrom. We obtained as follows:
density: 0.576983 g/cm^3
ASA_A^2: 3964.65 A^2
POAV: 13737.4 A^3
porosity or POAV_Volume_fraction: 0.77498

pk: 5

3. pk: 294 (CO2 only henry coeff)
pk: 329 (CH4, only hery coeff
)

4. pk: 373 (CO2), pk: 391 (CH4)

## 5) Binary mixture isotherms

In [4]:
import pyiast
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df_ch4 = pd.read_csv("CH4_IRMOF1.csv")
df_co2 = pd.read_csv("CO2_IRMOF1.csv")

In [2]:
df_ch4.head()

   Pressure(bar)  Loading(mmol/g)  Unnamed: 2  Unnamed: 3
0            0.1         0.010812         NaN         NaN
1            0.5         0.059352         NaN         NaN
2            0.9         0.104386         NaN         NaN
3            1.3         0.148186         NaN         NaN
4            1.7         0.198804         NaN         NaN

In [3]:
df_co2.head()

   Pressure(bar)  Loading(mmol/g)  Unnamed: 2  Unnamed: 3
0            0.1         0.053378         NaN         NaN
1            0.5         0.273871         NaN         NaN
2            0.9         0.505175         NaN         NaN
3            1.3         0.751415         NaN         NaN
4            1.7         1.009247         NaN         NaN

In [5]:
ch4_isotherm = pyiast.InterpolatorIsotherm(df_ch4,
                                    loading_key="Loading(mmol/g)",
                                    pressure_key="Pressure(bar)")

In [6]:
co2_isotherm = pyiast.InterpolatorIsotherm(df_co2,
                                    loading_key="Loading(mmol/g)",
                                    pressure_key="Pressure(bar)")